version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
      - POSTGRES_USER=ruskeyz
      - POSTGRES_DB=novat
    ports:
      - "5432:5432"
